# Block matrices

Consider an $N \times M$ matrix $\mathbf{A}$ given by:

$$\mathbf{A} 
= \begin{bmatrix}
\mathbf{A}_{11} & \cdots & \mathbf{A}_{1r} \\
\vdots & & \vdots  \\
\mathbf{A}_{q1} & \cdots & \mathbf{A}_{qr}
\end{bmatrix} \: ,
$$

where 

$$
N = \sum_{\alpha = 1}^{q} N_{\alpha} \: ,
$$

$$
M = \sum_{\beta = 1}^{r} M_{\beta}
$$

and $\mathbf{A}_{\alpha \beta}$ are $N_{\alpha} \times M_{\beta}$ submatrices, $\alpha = 1, \dots, q$, $\beta = 1, \dots, r$, defined as follows:

$$
\mathbf{A}_{\alpha \beta} =
\begin{bmatrix}
a_{11}^{(\alpha \beta)} & \cdots & a_{1 M_{\beta}}^{(\alpha \beta)} \\
\vdots & & \vdots \\
a_{N_{\alpha} 1}^{(\alpha \beta)} & \cdots & a_{N_{\alpha} M_{\beta}}^{(\alpha \beta)}
\end{bmatrix} \: .
$$

The matrix $\mathbf{A}$, formed by the submatrices $\mathbf{A}_{\alpha \beta}$, is an example of **block matrix**. The figure below shows an example of a block matrix $\mathbf{A}$ and its tranpose $\mathbf{A}^{\top}$, where $q = 2$, $r = 3$, $M = M_{1} + M_{2} + M_{3}$ and $N = N_{1} + N_{2}$.

<img src='block_matrices_1.png' width = 700>

### Multiplying a block matrix by a scalar

It can be easily shown that:

$$
\mu \mathbf{A} = \begin{bmatrix}
\mu \mathbf{A}_{11} & \cdots & \mu \mathbf{A}_{1r} \\
\vdots & & \vdots  \\
\mu \mathbf{A}_{q1} & \cdots & \mu \mathbf{A}_{qr}
\end{bmatrix} \: ,
$$

where $\mu$ is a constant. 

### Adding two block matrices

Let's consider another $N \times M$ matrix $\mathbf{B}$ given by:

$$\mathbf{B} 
= \begin{bmatrix}
\mathbf{B}_{11} & \cdots & \mathbf{B}_{1r} \\
\vdots & & \vdots  \\
\mathbf{B}_{q1} & \cdots & \mathbf{B}_{qr}
\end{bmatrix} \: ,
$$

where $\mathbf{B}_{\alpha \beta}$ are $N_{\alpha} \times M_{\beta}$ submatrices, $\alpha = 1, \dots, q$, $\beta = 1, \dots, r$, defined as follows:

$$
\mathbf{B}_{\alpha \beta} =
\begin{bmatrix}
b_{11}^{(\alpha \beta)} & \cdots & b_{1 M_{\beta}}^{(\alpha \beta)} \\
\vdots & & \vdots \\
b_{N_{\alpha} 1}^{(\alpha \beta)} & \cdots & b_{N_{\alpha} M_{\beta}}^{(\alpha \beta)}
\end{bmatrix} \: .
$$

Notice that, in this case, a resultant $N \times M$ matrix $\mathbf{C}$ can be defined by adding the submatrices $\mathbf{A}_{\alpha \beta}$ and $\mathbf{B}_{\alpha \beta}$, so that:

$$\mathbf{C} 
= \begin{bmatrix}
\mathbf{C}_{11} & \cdots & \mathbf{C}_{1r} \\
\vdots & & \vdots  \\
\mathbf{C}_{q1} & \cdots & \mathbf{C}_{qr}
\end{bmatrix} \: ,
$$

where $\mathbf{C_{\alpha \beta}} = \mathbf{A}_{\alpha \beta} + \mathbf{B}_{\alpha \beta}$, $\alpha = 1, \dots, q$, $\beta = 1, \dots, r$.

**Be careful!**

The next figure illustrates three block matrices $\mathbf{A}$, $\mathbf{B}$ and $\mathbf{D}$. These three matrices are $N \times M$. Let's consider a resultant matrix obtained by adding the elements of $\mathbf{A}$ and $\mathbf{B}$. In this case, the submatrices forming $\mathbf{A}$ and $\mathbf{B}$ have exactly the same shape. Consequently, the resultant matrix $\mathbf{C}$ can be defined by adding the submatrices of $\mathbf{A}$ and $\mathbf{B}$. Consider now the case in which a matrix $\mathbf{C}$ is obtained by adding the block matrices $\mathbf{A}$ and $\mathbf{D}$. In this case, the resultant matrix $\mathbf{C}$ cannot be defined by adding the submatrices of $\mathbf{A}$ and $\mathbf{D}$ because they do not have exactly the same shape. However, it is still possible to define $\mathbf{C}$ as the sum of $\mathbf{A}$ and $\mathbf{D}$ because these two block matrices are $N \times M$.

<img src='block_matrices_2.png' width = 700>

### Product of two block matrices

Let $\mathbf{A}$ and $\mathbf{B}$ be two block matrices given by

$$\mathbf{A} 
= \begin{bmatrix}
\mathbf{A}_{11} & \cdots & \mathbf{A}_{1r} \\
\vdots & & \vdots  \\
\mathbf{A}_{q1} & \cdots & \mathbf{A}_{qr}
\end{bmatrix}
$$

and

$$\mathbf{B} 
= \begin{bmatrix}
\mathbf{B}_{11} & \cdots & \mathbf{B}_{1s} \\
\vdots & & \vdots  \\
\mathbf{B}_{r1} & \cdots & \mathbf{B}_{rs}
\end{bmatrix} \: ,
$$

where $\mathbf{A}_{\alpha \beta}$ and $\mathbf{B}_{\beta \gamma}$ are, respectively, $N_{\alpha} \times M_{\beta}$ and $M_{\beta} \times L_{\gamma}$ submatrices, $\alpha = 1, \dots, q$, $\beta = 1, \dots, r$, $\gamma = 1, \dots, s$,

$$
N = \sum_{\alpha = 1}^{q} N_{\alpha} \: ,
$$

$$
M = \sum_{\beta = 1}^{r} M_{\beta}
$$

and

$$
L = \sum_{\gamma = 1}^{s} L_{\gamma} \: .
$$

In this case, the resultant $N \times L$ matrix $\mathbf{C}$ obtained by the product $\mathbf{A}\mathbf{B}$ is given by

$$\mathbf{C} 
= \begin{bmatrix}
\mathbf{C}_{11} & \cdots & \mathbf{C}_{1s} \\
\vdots & & \vdots  \\
\mathbf{C}_{q1} & \cdots & \mathbf{C}_{qs}
\end{bmatrix} \: ,
$$

where $\mathbf{C}_{\alpha \gamma}$ are $N_{\alpha} \times L_{\gamma}$ submatrices.

The figure below shows a particular case in which the resultant matrix $\matrix{C}$ is given by

$$
\mathbf{C} = \begin{bmatrix}
\mathbf{C}_{11} & \mathbf{C}_{12} \\
\mathbf{C}_{21} & \mathbf{C}_{22}
\end{bmatrix} \: ,
$$

where

$$
\mathbf{C}_{\alpha \beta} = \sum_{\beta = 1}^{3} \mathbf{A}_{\alpha\beta} \mathbf{B}_{\beta\gamma} \: .
$$

The figure below also illustrates how the submatrix $\mathbf{C}_{11}$ is computed. 

<img src='block_matrices_3.png' width = 700>

Let's now consider two particular cases. In both cases, the matrices $\mathbf{B}$ and $\mathbf{C}$ are replaced by vectors $\mathbf{b}$ and $\mathbf{c}$, respectively, as follows:

$$
\mathbf{A} \mathbf{b} = \mathbf{c} \: .
$$

In the first case, the matrix $\mathbf{A}$ is partitioned into columns and the vector $\mathbf{b}$ is divided into three vectors:

<img src='block_matrices_4.png' width = 700>

Consider an $N \times M$ matrix $\mathbf{A}$ formed by $r$ blocks with $M_{\beta}$ columns each, $\beta = 1, \dots, r$, $M = \sum\limits_{\beta = 1}^{r} M_{\beta}$.

In the next example, the matrix $\mathbf{A}$ is partitioned into rows and the vector $\mathbf{c}$ is divided into two vectors:

<img src='block_matrices_5.png' width = 700>

Consider an $N \times M$ matrix $\mathbf{A}$ formed by $q$ blocks with $N_{\alpha}$ rows each, $\alpha = 1, \dots, q$, $N = \sum\limits_{\alpha = 1}^{q} N_{\alpha}$.

### Exercise

Let $\mathbf{A}$ and $\mathbf{B}$ be two complex matrices given by:

$$
\mathbf{A} = \tilde{\mathbf{A}} + i \, \breve{\mathbf{A}}
$$

and

$$
\mathbf{B} = \tilde{\mathbf{B}} + i \, \breve{\mathbf{B}} \: ,
$$

where $i = \sqrt{-1}$. 

Let's consider that the complex matrix $\mathbf{C} = \tilde{\mathbf{C}} + i \, \breve{\mathbf{C}}$ obtained by the product of $\mathbf{A}$ and $\mathbf{B}$. In this case, show that the relationship between the submatrices $\tilde{\mathbf{A}}$, $\tilde{\mathbf{B}}$, $\tilde{\mathbf{C}}$, $\breve{\mathbf{A}}$, $\breve{\mathbf{B}}$ and $\breve{\mathbf{C}}$ is given by:

$$
\begin{bmatrix}
\tilde{\mathbf{C}} \\
\breve{\mathbf{C}}
\end{bmatrix} =
\begin{bmatrix}
\tilde{\mathbf{A}} & -\breve{\mathbf{A}} \\
\breve{\mathbf{A}} &  \tilde{\mathbf{A}}
\end{bmatrix}
\begin{bmatrix}
\tilde{\mathbf{B}} \\
\breve{\mathbf{B}}
\end{bmatrix} \: .
$$

If instead of a matrix $\mathbf{B}$ we have a vector

$$
\mathbf{b} = \tilde{\mathbf{b}} + i \, \breve{\mathbf{b}} \: ,
$$

the relationship given above can be simplified as follows:

$$
\begin{bmatrix}
\tilde{\mathbf{c}} \\
\breve{\mathbf{c}}
\end{bmatrix} =
\begin{bmatrix}
\tilde{\mathbf{A}} & -\breve{\mathbf{A}} \\
\breve{\mathbf{A}} &  \tilde{\mathbf{A}}
\end{bmatrix}
\begin{bmatrix}
\tilde{\mathbf{b}} \\
\breve{\mathbf{b}}
\end{bmatrix} \: ,
$$

where $\tilde{\mathbf{c}}$ and $\breve{\mathbf{c}}$ are the real and imaginary parts of the resulting vector $\mathbf{c}$.

#### Dealing with complex arrays

In [1]:
import numpy as np

In [2]:
N = 5

In [3]:
A_real = 10*np.around(np.random.rand(N,N), decimals=3)
A_imaginary = 10*np.around(np.random.rand(N,N), decimals=3)

In [4]:
A_real

array([[0.08, 3.02, 0.1 , 0.5 , 8.22],
       [1.86, 6.69, 1.5 , 9.79, 0.49],
       [4.75, 2.27, 5.66, 0.33, 7.47],
       [6.57, 8.55, 2.71, 9.92, 7.6 ],
       [3.15, 1.76, 2.31, 2.77, 6.98]])

In [5]:
A_imaginary

array([[3.  , 3.08, 0.77, 8.84, 6.41],
       [4.46, 3.37, 6.99, 4.28, 0.14],
       [0.09, 6.51, 9.78, 6.65, 0.5 ],
       [0.41, 4.92, 0.72, 0.08, 7.4 ],
       [7.77, 1.45, 9.32, 8.96, 3.42]])

In [6]:
A = A_real + 1j*A_imaginary

In [7]:
A

array([[0.08+3.j  , 3.02+3.08j, 0.1 +0.77j, 0.5 +8.84j, 8.22+6.41j],
       [1.86+4.46j, 6.69+3.37j, 1.5 +6.99j, 9.79+4.28j, 0.49+0.14j],
       [4.75+0.09j, 2.27+6.51j, 5.66+9.78j, 0.33+6.65j, 7.47+0.5j ],
       [6.57+0.41j, 8.55+4.92j, 2.71+0.72j, 9.92+0.08j, 7.6 +7.4j ],
       [3.15+7.77j, 1.76+1.45j, 2.31+9.32j, 2.77+8.96j, 6.98+3.42j]])

In [8]:
A.real

array([[0.08, 3.02, 0.1 , 0.5 , 8.22],
       [1.86, 6.69, 1.5 , 9.79, 0.49],
       [4.75, 2.27, 5.66, 0.33, 7.47],
       [6.57, 8.55, 2.71, 9.92, 7.6 ],
       [3.15, 1.76, 2.31, 2.77, 6.98]])

In [9]:
A.imag

array([[3.  , 3.08, 0.77, 8.84, 6.41],
       [4.46, 3.37, 6.99, 4.28, 0.14],
       [0.09, 6.51, 9.78, 6.65, 0.5 ],
       [0.41, 4.92, 0.72, 0.08, 7.4 ],
       [7.77, 1.45, 9.32, 8.96, 3.42]])

In [13]:
np.conjugate(A)

array([[0.08-3.j  , 3.02-3.08j, 0.1 -0.77j, 0.5 -8.84j, 8.22-6.41j],
       [1.86-4.46j, 6.69-3.37j, 1.5 -6.99j, 9.79-4.28j, 0.49-0.14j],
       [4.75-0.09j, 2.27-6.51j, 5.66-9.78j, 0.33-6.65j, 7.47-0.5j ],
       [6.57-0.41j, 8.55-4.92j, 2.71-0.72j, 9.92-0.08j, 7.6 -7.4j ],
       [3.15-7.77j, 1.76-1.45j, 2.31-9.32j, 2.77-8.96j, 6.98-3.42j]])

In [14]:
np.conjugate(A).T

array([[0.08-3.j  , 1.86-4.46j, 4.75-0.09j, 6.57-0.41j, 3.15-7.77j],
       [3.02-3.08j, 6.69-3.37j, 2.27-6.51j, 8.55-4.92j, 1.76-1.45j],
       [0.1 -0.77j, 1.5 -6.99j, 5.66-9.78j, 2.71-0.72j, 2.31-9.32j],
       [0.5 -8.84j, 9.79-4.28j, 0.33-6.65j, 9.92-0.08j, 2.77-8.96j],
       [8.22-6.41j, 0.49-0.14j, 7.47-0.5j , 7.6 -7.4j , 6.98-3.42j]])